# Generated by Django 2.2 on 2021-07-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration', models.ImageField(upload_to='vehicle_registration/')),
                ('vehicle_insurance', models.ImageField(upload_to='vehicle_insurance/')),
                ('vehicle_permit', models.ImageField(upload_to='vehicle_permit/')),
                ('vehicle_photo', models.ImageField(upload_to='vehicle_photo/')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.DriverInfo')),
            ],
        ),
    ]
