# Generated by Django 2.2 on 2021-07-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
