# Generated by Django 2.2 on 2021-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=200)),
                ('photoid', models.ImageField(upload_to='photoid/')),
                ('driving_license', models.ImageField(upload_to='licenses/')),
                ('phone_no', models.BigIntegerField(unique=True)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
